#!/usr/bin/env ruby
require 'json'


# Read in settings
begin
  serialized = File.read("/etc/vnstat-alert.json")
  data = JSON.parse(serialized)
  limit = data["limit"].to_i
rescue
  puts "Please create a /etc/vnstat-alert.json file"
  exit
end

puts limit


